import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  ar: {
    // Navbar
    nav_home: 'الرئيسية',
    nav_clothes: 'الملابس',
    nav_shoes: 'الأحذية',
    nav_bags: 'الحقائب',
    nav_beauty: 'التجميل',
    nav_more: 'المزيد',
    nav_signin: 'تسجيل الدخول',
    nav_signout: 'تسجيل الخروج',
    nav_admin: 'لوحة الإدارة',
    nav_search_placeholder: 'ابحثي عن فساتين، أحذية، حقائب...',
    nav_search_btn: 'بحث',
    nav_announcement: 'توصيل مجاني للطلبات فوق 100,000 دينار | وصول جديد كل أسبوع!',

    // Hero
    hero_badge: 'مجموعة صيف 2024 الجديدة',
    hero_title_1: 'اكتشفي',
    hero_title_2: 'أسلوبكِ المثالي',
    hero_desc: 'استكشفي مجموعتنا المختارة من الأزياء والجمال ومستلزمات الحياة. مصممة للمرأة العراقية العصرية.',
    hero_shop_now: 'تسوقي الآن',
    hero_beauty_edit: 'عالم التجميل',
    hero_stat_products: 'منتج',
    hero_stat_customers: 'عميلة سعيدة',
    hero_stat_rating: 'تقييم',
    hero_floating: 'منتج جديد هذا الأسبوع',

    // Perks
    perk_delivery: 'توصيل مجاني',
    perk_delivery_desc: 'للطلبات فوق 100,000 دينار',
    perk_secure: 'دفع آمن',
    perk_secure_desc: 'طرق دفع متعددة وآمنة',
    perk_returns: 'إرجاع سهل',
    perk_returns_desc: 'إرجاع مجاني خلال 7 أيام',
    perk_quality: 'جودة مختارة',
    perk_quality_desc: 'منتخبة بعناية لكِ',

    // Categories
    cat_title: 'تسوقي حسب الفئة',
    cat_desc: 'اجدي كل ما تحتاجينه في مكان واحد',
    cat_clothes: 'الملابس',
    cat_clothes_desc: 'فساتين، بلوزات، عبايات والمزيد',
    cat_shoes: 'الأحذية',
    cat_shoes_desc: 'كعب، باليرينا، رياضي والمزيد',
    cat_bags: 'الحقائب',
    cat_bags_desc: 'توت، كراس، كروس بودي والمزيد',
    cat_foundation: 'التجميل',
    cat_foundation_desc: 'كريم أساس، بودرة، بي بي كريم والمزيد',
    cat_other: 'الإكسسوارات',
    cat_other_desc: 'إكسسوارات، إلكترونيات والمزيد',

    // Featured
    featured_title: 'المنتجات المميزة',
    featured_desc: 'مختارة خصيصاً لكِ',
    view_all: 'عرض الكل',

    // New Arrivals
    new_arrivals_title: 'أحدث الوصولات',
    new_arrivals_desc: 'آخر ما وصل إلى متجرنا',
    new_arrivals_badge: 'جديد',

    // Promo banner
    promo_limited: 'عرض محدود',
    promo_title: 'تخفيضات الصيف',
    promo_desc: 'خصم يصل إلى 40% على منتجات مختارة',
    promo_btn: 'تسوقي العروض',

    // Product card
    quick_add: 'إضافة سريعة',
    added: 'تمت الإضافة!',
    out_of_stock: 'نفد المخزون',
    only_left: 'فقط {n} متبقي',

    // Cart
    cart_title: 'سلة التسوق',
    cart_items: 'منتجات',
    cart_empty: 'سلة التسوق فارغة',
    cart_empty_desc: 'أضيفي منتجات جميلة!',
    cart_continue: 'متابعة التسوق',
    cart_subtotal: 'المجموع الفرعي',
    cart_shipping: 'الشحن يحسب عند الدفع',
    cart_checkout: 'المتابعة للدفع',
    cart_clear: 'مسح السلة',
    cart_size: 'المقاس',
    cart_color: 'اللون',

    // Product page
    size_guide: 'دليل المقاسات',
    size_label: 'المقاس',
    color_label: 'اللون',
    quantity_label: 'الكمية',
    add_to_cart: 'إضافة للسلة',
    buy_now: 'شراء الآن',
    reviews: 'تقييم',
    free_delivery: 'توصيل مجاني للطلبات فوق 100,000 دينار',
    easy_returns: 'إرجاع سهل خلال 7 أيام',
    authentic: 'منتج أصلي مضمون',
    in_stock: 'في المخزون',

    // Checkout
    checkout_delivery: 'معلومات التوصيل',
    checkout_payment: 'الدفع',
    checkout_confirm: 'التأكيد',
    checkout_fullname: 'الاسم الكامل',
    checkout_phone: 'رقم الهاتف',
    checkout_email: 'البريد الإلكتروني',
    checkout_address: 'العنوان',
    checkout_city: 'المدينة',
    checkout_continue: 'المتابعة للدفع',
    checkout_back: 'العودة للتوصيل',
    checkout_secure: 'دفع آمن',
    checkout_place_order: 'تأكيد الطلب',
    checkout_success_title: 'تم الطلب بنجاح! 🎉',
    checkout_success_desc: 'شكراً لتسوقكِ من ساسا بوتيك',
    checkout_order_id: 'رقم الطلب',
    checkout_continue_shopping: 'متابعة التسوق',
    checkout_track: 'تتبع الطلب',
    delivery_label: 'الدفع عند الاستلام',
    subtotal: 'المجموع الفرعي',
    delivery_fee: 'رسوم التوصيل',
    free: 'مجاني',
    total: 'الإجمالي',
    order_summary: 'ملخص الطلب',
    qty: 'الكمية',

    // Auth
    auth_welcome_back: 'مرحباً بعودتكِ!',
    auth_join: 'انضمي إلى ساسا',
    auth_signin_desc: 'سجلي الدخول إلى حسابكِ',
    auth_register_desc: 'أنشئي حسابكِ اليوم',
    auth_signin_tab: 'تسجيل الدخول',
    auth_register_tab: 'إنشاء حساب',
    auth_name: 'الاسم الكامل',
    auth_name_placeholder: 'اسمكِ',
    auth_email_placeholder: 'بريدكِ الإلكتروني',
    auth_password: 'كلمة المرور',
    auth_forgot: 'نسيتِ كلمة المرور؟',
    auth_signin_btn: 'تسجيل الدخول',
    auth_create_btn: 'إنشاء الحساب',
    auth_no_account: 'ليس لديكِ حساب؟',
    auth_have_account: 'لديكِ حساب بالفعل؟',
    auth_register_link: 'سجلي',
    auth_signin_link: 'سجلي الدخول',
    auth_admin_hint: 'حساب الإدارة: sasa@sasaboutique.com / sasab1992',
    auth_tagline: 'وجهتكِ للأزياء في العراق — مختارة بأناقة للمرأة العصرية.',

    // Footer
    footer_shop: 'التسوق',
    footer_help: 'المساعدة',
    footer_contact: 'التواصل',
    footer_track: 'تتبع الطلب',
    footer_returns: 'الإرجاع والاستبدال',
    footer_size_guide: 'دليل المقاسات',
    footer_faq: 'الأسئلة الشائعة',
    footer_contact_us: 'تواصلي معنا',
    footer_desc: 'وجهتكِ للأزياء والجمال ومستلزمات الحياة — مختارة بحب للمرأة العراقية.',
    footer_accept: 'طرق الدفع المقبولة',
    footer_rights: '© 2024 ساسا بوتيك. جميع الحقوق محفوظة.',
    footer_made: 'صُنع بـ ❤️ في العراق',
    footer_privacy: 'الخصوصية',
    footer_terms: 'الشروط',
    footer_cookies: 'الكوكيز',

    // Category page
    items_found: 'منتج',
    filters: 'الفلاتر',
    clear_all: 'مسح الكل',
    type_label: 'النوع',
    price_label: 'السعر (دينار)',
    sort_by: 'ترتيب حسب',
    sort_recommended: 'الموصى به',
    sort_newest: 'الأحدث',
    sort_price_asc: 'السعر: من الأقل',
    sort_price_desc: 'السعر: من الأعلى',
    no_products: 'لا توجد منتجات',
    no_products_desc: 'جربي تغيير الفلاتر',
    clear_filters: 'مسح الفلاتر',
    products_count: 'منتج',


    // Admin
    admin_dashboard: 'لوحة التحكم',
    admin_products: 'المنتجات',
    admin_orders: 'الطلبات',
    admin_customers: 'العملاء',
    admin_panel: 'لوحة الإدارة',
    admin_welcome: 'مرحباً بك! إليك ما يحدث في ساسا.',
    admin_revenue: 'إجمالي الإيرادات',
    admin_total_orders: 'إجمالي الطلبات',
    admin_total_products: 'إجمالي المنتجات',
    admin_total_customers: 'إجمالي العملاء',
    admin_recent_orders: 'أحدث الطلبات',
    admin_view_all: 'عرض الكل',
    admin_no_orders: 'لا توجد طلبات بعد',
    admin_category_overview: 'نظرة عامة على الفئات',
    admin_add_product: 'إضافة منتج',
    admin_edit_product: 'تعديل المنتج',
    admin_new_product: 'منتج جديد',
    admin_product_name: 'اسم المنتج',
    admin_category: 'الفئة',
    admin_type: 'النوع',
    admin_price: 'السعر (دينار)',
    admin_original_price: 'السعر الأصلي (اختياري)',
    admin_quantity: 'الكمية',
    admin_featured: 'مميز',
    admin_sizes: 'المقاسات (بفاصلة)',
    admin_colors: 'الألوان (بفاصلة)',
    admin_description: 'الوصف',
    admin_image: 'صورة المنتج',
    admin_upload: 'اضغط لرفع صورة (5MB حد أقصى)',
    admin_cancel: 'إلغاء',
    admin_save: 'حفظ',
    admin_update: 'تحديث المنتج',
    admin_create: 'إنشاء المنتج',
    admin_delete_confirm: 'هل تريدين حذف',
    admin_deleted: 'تم الحذف!',
    admin_updated: 'تم التحديث!',
    admin_created: 'تم الإنشاء!',
    admin_no_products: 'لا توجد منتجات بعد',
    admin_no_customers: 'لا يوجد عملاء بعد',
    admin_status_updated: 'تم تحديث الحالة!',
    admin_back_store: '← العودة للمتجر',
    admin_signout: 'تسجيل الخروج',
    admin_yes: 'نعم',
    admin_no: 'لا',
    admin_all: 'الكل',
    admin_items: 'منتج',
    admin_joined: 'انضم',
    admin_orders_count: 'الطلبات',
    admin_spent: 'المبلغ المنفق',
    admin_order_id: 'رقم الطلب',
    admin_customer: 'العميل',
    admin_payment: 'الدفع',
    admin_status: 'الحالة',
    admin_date: 'التاريخ',
    admin_actions: 'الإجراءات',
    admin_product_col: 'المنتج',
    admin_stock: 'المخزون',

    // General
    home: 'الرئيسية',
    currency: 'دينار',
    loading: 'جارٍ التحميل...',
    search_results: 'نتائج البحث',
  },
  en: {
    nav_home: 'Home',
    nav_clothes: 'Clothes',
    nav_shoes: 'Shoes',
    nav_bags: 'Bags',
    nav_beauty: 'Beauty',
    nav_more: 'More',
    nav_signin: 'Sign In',
    nav_signout: 'Sign Out',
    nav_admin: 'Admin Dashboard',
    nav_search_placeholder: 'Search dresses, shoes, bags...',
    nav_search_btn: 'Search',
    nav_announcement: 'Free delivery on orders over 100,000 IQD | New arrivals every week!',

    hero_badge: 'New Summer Collection 2024',
    hero_title_1: 'Discover Your',
    hero_title_2: 'Perfect Style',
    hero_desc: 'Explore our curated collection of fashion, beauty, and lifestyle essentials. Designed for the modern Iraqi woman.',
    hero_shop_now: 'Shop Now',
    hero_beauty_edit: 'Beauty Edit',
    hero_stat_products: 'Products',
    hero_stat_customers: 'Happy Customers',
    hero_stat_rating: 'Rating',
    hero_floating: 'New Items This Week',

    perk_delivery: 'Free Delivery',
    perk_delivery_desc: 'On orders over 100K IQD',
    perk_secure: 'Secure Payments',
    perk_secure_desc: 'Multiple safe payment options',
    perk_returns: 'Easy Returns',
    perk_returns_desc: '7-day hassle-free returns',
    perk_quality: 'Quality Curated',
    perk_quality_desc: 'Hand-picked for you',

    cat_title: 'Shop by Category',
    cat_desc: 'Find everything you need in one place',
    cat_clothes: 'Clothes',
    cat_clothes_desc: 'Dresses, blouses, abayas & more',
    cat_shoes: 'Shoes',
    cat_shoes_desc: 'Heels, flats, sneakers & more',
    cat_bags: 'Bags',
    cat_bags_desc: 'Totes, clutches, crossbody & more',
    cat_foundation: 'Beauty',
    cat_foundation_desc: 'Foundation, blush, BB cream & more',
    cat_other: 'Lifestyle',
    cat_other_desc: 'Accessories, electronics & more',

    featured_title: 'Featured Items',
    featured_desc: 'Handpicked just for you',
    view_all: 'View All',

    new_arrivals_title: 'New Arrivals',
    new_arrivals_desc: 'Just landed in our store',
    new_arrivals_badge: 'New',

    promo_limited: 'LIMITED TIME',
    promo_title: 'Summer Sale',
    promo_desc: 'Up to 40% off selected items',
    promo_btn: 'Shop Sale',

    quick_add: 'Quick Add',
    added: 'Added!',
    out_of_stock: 'Out of Stock',
    only_left: 'Only {n} left',

    cart_title: 'My Cart',
    cart_items: 'items',
    cart_empty: 'Your cart is empty',
    cart_empty_desc: 'Add some beautiful items!',
    cart_continue: 'Continue Shopping',
    cart_subtotal: 'Subtotal',
    cart_shipping: 'Shipping calculated at checkout',
    cart_checkout: 'Proceed to Checkout',
    cart_clear: 'Clear cart',
    cart_size: 'Size',
    cart_color: 'Color',

    size_guide: 'Size Guide',
    size_label: 'Size',
    color_label: 'Color',
    quantity_label: 'Quantity',
    add_to_cart: 'Add to Cart',
    buy_now: 'Buy Now',
    reviews: 'reviews',
    free_delivery: 'Free delivery on orders over 100,000 IQD',
    easy_returns: '7-day easy returns',
    authentic: 'Authentic product guaranteed',
    in_stock: 'in stock',

    checkout_delivery: 'Delivery Information',
    checkout_payment: 'Payment',
    checkout_confirm: 'Confirmation',
    checkout_fullname: 'Full Name',
    checkout_phone: 'Phone',
    checkout_email: 'Email',
    checkout_address: 'Address',
    checkout_city: 'City',
    checkout_continue: 'Continue to Payment',
    checkout_back: 'Back to delivery',
    checkout_secure: 'Secure Payment',
    checkout_place_order: 'Place Order',
    checkout_success_title: 'Order Placed! 🎉',
    checkout_success_desc: 'Thank you for shopping at SASA Boutique',
    checkout_order_id: 'Order ID',
    checkout_continue_shopping: 'Continue Shopping',
    checkout_track: 'Track Order',
    delivery_label: 'Cash on Delivery',
    subtotal: 'Subtotal',
    delivery_fee: 'Delivery',
    free: 'Free',
    total: 'Total',
    order_summary: 'Order Summary',
    qty: 'Qty',

    auth_welcome_back: 'Welcome back!',
    auth_join: 'Join SASA',
    auth_signin_desc: 'Sign in to your account',
    auth_register_desc: 'Create your account today',
    auth_signin_tab: 'Sign In',
    auth_register_tab: 'Register',
    auth_name: 'Full Name',
    auth_name_placeholder: 'Your name',
    auth_email_placeholder: 'your@email.com',
    auth_password: 'Password',
    auth_forgot: 'Forgot password?',
    auth_signin_btn: 'Sign In',
    auth_create_btn: 'Create Account',
    auth_no_account: "Don't have an account?",
    auth_have_account: 'Already have an account?',
    auth_register_link: 'Register',
    auth_signin_link: 'Sign In',
    auth_admin_hint: 'Admin demo: sasa@sasaboutique.com / sasab1992',
    auth_tagline: 'Your fashion destination in Iraq — curated with elegance for the modern woman.',

    footer_shop: 'Shop',
    footer_help: 'Help',
    footer_contact: 'Contact',
    footer_track: 'Track Order',
    footer_returns: 'Returns & Exchanges',
    footer_size_guide: 'Size Guide',
    footer_faq: 'FAQ',
    footer_contact_us: 'Contact Us',
    footer_desc: 'Your destination for fashion, beauty, and lifestyle — curated with love for the Iraqi woman.',
    footer_accept: 'We accept',
    footer_rights: '© 2024 SASA Boutique. All rights reserved.',
    footer_made: 'Made with ❤️ in Iraq',
    footer_privacy: 'Privacy',
    footer_terms: 'Terms',
    footer_cookies: 'Cookies',

    items_found: 'items found',
    filters: 'Filters',
    clear_all: 'Clear all',
    type_label: 'Type',
    price_label: 'Price (IQD)',
    sort_by: 'Sort By',
    sort_recommended: 'Recommended',
    sort_newest: 'Newest',
    sort_price_asc: 'Price: Low to High',
    sort_price_desc: 'Price: High to Low',
    no_products: 'No products found',
    no_products_desc: 'Try adjusting your filters',
    clear_filters: 'Clear Filters',
    products_count: 'products',


    // Admin
    admin_dashboard: 'Dashboard',
    admin_products: 'Products',
    admin_orders: 'Orders',
    admin_customers: 'Customers',
    admin_panel: 'Admin Panel',
    admin_welcome: 'Welcome back! Here\'s what\'s happening at SASA.',
    admin_revenue: 'Total Revenue',
    admin_total_orders: 'Total Orders',
    admin_total_products: 'Products',
    admin_total_customers: 'Customers',
    admin_recent_orders: 'Recent Orders',
    admin_view_all: 'View All',
    admin_no_orders: 'No orders yet',
    admin_category_overview: 'Category Overview',
    admin_add_product: 'Add Product',
    admin_edit_product: 'Edit Product',
    admin_new_product: 'New Product',
    admin_product_name: 'Product Name',
    admin_category: 'Category',
    admin_type: 'Type',
    admin_price: 'Price (IQD)',
    admin_original_price: 'Original Price (optional)',
    admin_quantity: 'Quantity',
    admin_featured: 'Featured',
    admin_sizes: 'Sizes (comma-separated)',
    admin_colors: 'Colors (comma-separated)',
    admin_description: 'Description',
    admin_image: 'Product Image',
    admin_upload: 'Click to upload image (max 5MB)',
    admin_cancel: 'Cancel',
    admin_save: 'Save',
    admin_update: 'Update Product',
    admin_create: 'Create Product',
    admin_delete_confirm: 'Delete',
    admin_deleted: 'Deleted!',
    admin_updated: 'Product updated!',
    admin_created: 'Product created!',
    admin_no_products: 'No products yet',
    admin_no_customers: 'No customers yet',
    admin_status_updated: 'Status updated!',
    admin_back_store: '← Back to Store',
    admin_signout: 'Sign Out',
    admin_yes: 'Yes',
    admin_no: 'No',
    admin_all: 'All',
    admin_items: 'items',
    admin_joined: 'Joined',
    admin_orders_count: 'Orders',
    admin_spent: 'Total Spent',
    admin_order_id: 'Order ID',
    admin_customer: 'Customer',
    admin_payment: 'Payment',
    admin_status: 'Status',
    admin_date: 'Date',
    admin_actions: 'Actions',
    admin_product_col: 'Product',
    admin_stock: 'Stock',

    home: 'Home',
    currency: 'IQD',
    loading: 'Loading...',
    search_results: 'Search',
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('sasa_lang') || 'ar');

  useEffect(() => {
    localStorage.setItem('sasa_lang', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => translations[lang][key] || translations['en'][key] || key;
  const toggleLang = () => setLang(l => l === 'ar' ? 'en' : 'ar');
  const isRTL = lang === 'ar';

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);

// Admin translations (appended)
